### ISSUE TITLE
Application Class

### ISSUE THREAD

**Issue by irgalieri** [nachonerd/markdownblog#2]
## New Feature
- Extends from Silex/Application
- Given one routes.yml (Yaml File) prepare the controller providers (instance of Silex\ControllerProviderInterface).
- Given one errors.yml prepare the error pages.

**routes.yml eg:**

``` yaml
# routes.yml
home:
    paths:
        - /home
        - /
    _provider: 'Home'
post:
    paths:
        - /post
    _provider: 'Post'
about:
    paths:
        - /about
    _provider: 'About'
```

**errors.yml eg:**

``` yaml
# errors.yml
404:
    page: 404.html.twg
default:
    page: other.html.twg
```
